[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/admin"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "3001"